-- Fix existing 404 source links and expand the PHB/SRD-ish catalog.
-- 5e14 URL scheme (discovered from listing pages, not invented slugs):
--   https://5e14.dnd.su/{type}/{numericId}-{english-slug}/
--   type = class | race | backgrounds | spells | items
-- Subclasses and class/race features have no dedicated 5e14 pages; they link to the parent listing page.
-- 5eapi EN URLs are stored only when the endpoint returns 200 (e.g. backgrounds besides acolyte do not).

UPDATE catalog_races SET source_url_ru = 'https://5e14.dnd.su/race/81-human/' WHERE slug = 'human';
UPDATE catalog_races SET source_url_ru = 'https://5e14.dnd.su/race/78-dwarf/' WHERE slug = 'hill-dwarf';
UPDATE catalog_races SET source_url_ru = 'https://5e14.dnd.su/race/79-elf/' WHERE slug = 'high-elf';

UPDATE catalog_backgrounds SET source_url = 'https://www.dnd5eapi.co/api/2014/backgrounds/acolyte', source_url_ru = 'https://5e14.dnd.su/backgrounds/766-acolyte/' WHERE slug = 'acolyte';
UPDATE catalog_backgrounds SET source_url = '', source_url_ru = 'https://5e14.dnd.su/backgrounds/767-soldier/' WHERE slug = 'soldier';
UPDATE catalog_backgrounds SET source_url = '', source_url_ru = 'https://5e14.dnd.su/backgrounds/762-sage/' WHERE slug = 'sage';

UPDATE catalog_classes SET source_url_ru = 'https://5e14.dnd.su/class/91-fighter/' WHERE slug = 'fighter';
UPDATE catalog_classes SET source_url_ru = 'https://5e14.dnd.su/class/105-wizard/' WHERE slug = 'wizard';
UPDATE catalog_classes SET source_url_ru = 'https://5e14.dnd.su/class/89-cleric/' WHERE slug = 'cleric';

UPDATE catalog_subclasses SET source_url_ru = 'https://5e14.dnd.su/class/91-fighter/' WHERE slug IN ('champion', 'battle-master');
UPDATE catalog_subclasses SET source_url_ru = 'https://5e14.dnd.su/class/105-wizard/' WHERE slug IN ('evocation', 'abjuration');
UPDATE catalog_subclasses SET source_url_ru = 'https://5e14.dnd.su/class/89-cleric/' WHERE slug IN ('life', 'light');

UPDATE catalog_features SET source_url_ru = 'https://5e14.dnd.su/race/81-human/' WHERE slug = 'extra-language';
UPDATE catalog_features SET source_url_ru = 'https://5e14.dnd.su/race/78-dwarf/' WHERE slug IN ('dwarven-resilience', 'dwarven-toughness');
UPDATE catalog_features SET source_url_ru = 'https://5e14.dnd.su/race/79-elf/' WHERE slug IN ('darkvision', 'elf-cantrip');

UPDATE catalog_features SET source_url = 'https://www.dnd5eapi.co/api/2014/backgrounds/acolyte', source_url_ru = 'https://5e14.dnd.su/backgrounds/766-acolyte/' WHERE slug = 'shelter-of-the-faithful';
UPDATE catalog_features SET source_url = '', source_url_ru = 'https://5e14.dnd.su/backgrounds/767-soldier/' WHERE slug = 'military-rank';
UPDATE catalog_features SET source_url = '', source_url_ru = 'https://5e14.dnd.su/backgrounds/762-sage/' WHERE slug = 'researcher';

UPDATE catalog_features SET source_url_ru = 'https://5e14.dnd.su/class/91-fighter/'
 WHERE slug IN ('fighting-style', 'second-wind', 'action-surge', 'martial-archetype', 'fighter-asi-4', 'improved-critical', 'combat-superiority');
UPDATE catalog_features SET source_url_ru = 'https://5e14.dnd.su/class/105-wizard/'
 WHERE slug IN ('wizard-spellcasting', 'arcane-recovery', 'arcane-tradition', 'wizard-asi-4', 'evocation-savant', 'sculpt-spells', 'abjuration-savant', 'arcane-ward');
UPDATE catalog_features SET source_url_ru = 'https://5e14.dnd.su/class/89-cleric/'
 WHERE slug IN ('cleric-spellcasting', 'divine-domain', 'channel-divinity', 'cleric-asi-4', 'disciple-of-life', 'warding-flare');

INSERT INTO catalog_races (id, slug, name_en, name_ru, source_url, source_url_ru, ability_bonuses, speed, hp_bonus_per_level) VALUES
(4, 'mountain-dwarf', 'Mountain Dwarf', 'Горный дварф',
 'https://www.dnd5eapi.co/api/2014/races/dwarf', 'https://5e14.dnd.su/race/78-dwarf/',
 '{"con":2,"str":2}', 25, 0),
(5, 'wood-elf', 'Wood Elf', 'Лесной эльф',
 'https://www.dnd5eapi.co/api/2014/races/elf', 'https://5e14.dnd.su/race/79-elf/',
 '{"dex":2,"wis":1}', 35, 0),
(6, 'lightfoot-halfling', 'Lightfoot Halfling', 'Легконогий полурослик',
 'https://www.dnd5eapi.co/api/2014/subraces/lightfoot-halfling', 'https://5e14.dnd.su/race/80-halfling/',
 '{"dex":2,"cha":1}', 25, 0),
(7, 'rock-gnome', 'Rock Gnome', 'Скальный гном',
 'https://www.dnd5eapi.co/api/2014/subraces/rock-gnome', 'https://5e14.dnd.su/race/83-gnome/',
 '{"int":2,"con":1}', 25, 0),
(8, 'dragonborn', 'Dragonborn', 'Драконорождённый',
 'https://www.dnd5eapi.co/api/2014/races/dragonborn', 'https://5e14.dnd.su/race/82-dragonborn/',
 '{"str":2,"cha":1}', 30, 0),
(9, 'half-elf', 'Half-Elf', 'Полуэльф',
 'https://www.dnd5eapi.co/api/2014/races/half-elf', 'https://5e14.dnd.su/race/84-half-elf/',
 '{"cha":2}', 30, 0),
(10, 'half-orc', 'Half-Orc', 'Полуорк',
 'https://www.dnd5eapi.co/api/2014/races/half-orc', 'https://5e14.dnd.su/race/85-half-orc/',
 '{"str":2,"con":1}', 30, 0),
(11, 'tiefling', 'Tiefling', 'Тифлинг',
 'https://www.dnd5eapi.co/api/2014/races/tiefling', 'https://5e14.dnd.su/race/86-tiefling/',
 '{"int":1,"cha":2}', 30, 0);

INSERT INTO catalog_backgrounds (id, slug, name_en, name_ru, source_url, source_url_ru, ability_bonuses) VALUES
(4, 'charlatan', 'Charlatan', 'Шарлатан',
 '', 'https://5e14.dnd.su/backgrounds/769-charlatan/', '{}'),
(5, 'criminal', 'Criminal', 'Преступник',
 '', 'https://5e14.dnd.su/backgrounds/765-criminal/', '{}'),
(6, 'folk-hero', 'Folk Hero', 'Народный герой',
 '', 'https://5e14.dnd.su/backgrounds/763-folk-hero/', '{}'),
(7, 'sailor', 'Sailor', 'Моряк',
 '', 'https://5e14.dnd.su/backgrounds/761-sailor/', '{}'),
(8, 'urchin', 'Urchin', 'Беспризорник',
 '', 'https://5e14.dnd.su/backgrounds/758-urchin/', '{}'),
(9, 'entertainer', 'Entertainer', 'Артист',
 '', 'https://5e14.dnd.su/backgrounds/757-entertainer/', '{}'),
(10, 'guild-artisan', 'Guild Artisan', 'Гильдейский ремесленник',
 '', 'https://5e14.dnd.su/backgrounds/760-guild-artisan/', '{}'),
(11, 'noble', 'Noble', 'Благородный',
 '', 'https://5e14.dnd.su/backgrounds/759-noble/', '{}'),
(12, 'hermit', 'Hermit', 'Отшельник',
 '', 'https://5e14.dnd.su/backgrounds/764-hermit/', '{}'),
(13, 'outlander', 'Outlander', 'Чужеземец',
 '', 'https://5e14.dnd.su/backgrounds/768-outlander/', '{}');

INSERT INTO catalog_classes (id, slug, name_en, name_ru, hit_die, subclass_level, asi_levels, source_url, source_url_ru, ability_bonuses) VALUES
(4, 'barbarian', 'Barbarian', 'Варвар', 12, 3, '[4,8,12,16,19]',
 'https://www.dnd5eapi.co/api/2014/classes/barbarian', 'https://5e14.dnd.su/class/87-barbarian/', '{}'),
(5, 'bard', 'Bard', 'Бард', 8, 3, '[4,8,12,16,19]',
 'https://www.dnd5eapi.co/api/2014/classes/bard', 'https://5e14.dnd.su/class/88-bard/', '{}'),
(6, 'druid', 'Druid', 'Друид', 8, 2, '[4,8,12,16,19]',
 'https://www.dnd5eapi.co/api/2014/classes/druid', 'https://5e14.dnd.su/class/90-druid/', '{}'),
(7, 'monk', 'Monk', 'Монах', 8, 3, '[4,8,12,16,19]',
 'https://www.dnd5eapi.co/api/2014/classes/monk', 'https://5e14.dnd.su/class/93-monk/', '{}'),
(8, 'paladin', 'Paladin', 'Паладин', 10, 3, '[4,8,12,16,19]',
 'https://www.dnd5eapi.co/api/2014/classes/paladin', 'https://5e14.dnd.su/class/94-paladin/', '{}'),
(9, 'ranger', 'Ranger', 'Следопыт', 10, 3, '[4,8,12,16,19]',
 'https://www.dnd5eapi.co/api/2014/classes/ranger', 'https://5e14.dnd.su/class/97-ranger/', '{}'),
(10, 'rogue', 'Rogue', 'Плут', 8, 3, '[4,8,10,12,16,19]',
 'https://www.dnd5eapi.co/api/2014/classes/rogue', 'https://5e14.dnd.su/class/99-rogue/', '{}'),
(11, 'sorcerer', 'Sorcerer', 'Чародей', 6, 1, '[4,8,12,16,19]',
 'https://www.dnd5eapi.co/api/2014/classes/sorcerer', 'https://5e14.dnd.su/class/101-sorcerer/', '{}'),
(12, 'warlock', 'Warlock', 'Колдун', 8, 1, '[4,8,12,16,19]',
 'https://www.dnd5eapi.co/api/2014/classes/warlock', 'https://5e14.dnd.su/class/104-warlock/', '{}');

INSERT INTO catalog_subclasses (id, class_id, slug, name_en, name_ru, source_url, source_url_ru) VALUES
(7, 4, 'berserker', 'Path of the Berserker', 'Путь берсерка',
 'https://www.dnd5eapi.co/api/2014/subclasses/berserker', 'https://5e14.dnd.su/class/87-barbarian/'),
(8, 5, 'lore', 'College of Lore', 'Коллегия знаний',
 'https://www.dnd5eapi.co/api/2014/subclasses/lore', 'https://5e14.dnd.su/class/88-bard/'),
(9, 6, 'land', 'Circle of the Land', 'Круг земли',
 'https://www.dnd5eapi.co/api/2014/subclasses/land', 'https://5e14.dnd.su/class/90-druid/'),
(10, 7, 'open-hand', 'Way of the Open Hand', 'Путь открытой ладони',
 'https://www.dnd5eapi.co/api/2014/subclasses/open-hand', 'https://5e14.dnd.su/class/93-monk/'),
(11, 8, 'devotion', 'Oath of Devotion', 'Клятва преданности',
 'https://www.dnd5eapi.co/api/2014/subclasses/devotion', 'https://5e14.dnd.su/class/94-paladin/'),
(12, 9, 'hunter', 'Hunter', 'Охотник',
 'https://www.dnd5eapi.co/api/2014/subclasses/hunter', 'https://5e14.dnd.su/class/97-ranger/'),
(13, 10, 'thief', 'Thief', 'Вор',
 'https://www.dnd5eapi.co/api/2014/subclasses/thief', 'https://5e14.dnd.su/class/99-rogue/'),
(14, 11, 'draconic', 'Draconic Bloodline', 'Наследие драконов',
 'https://www.dnd5eapi.co/api/2014/subclasses/draconic', 'https://5e14.dnd.su/class/101-sorcerer/'),
(15, 12, 'fiend', 'The Fiend', 'Исчадие',
 'https://www.dnd5eapi.co/api/2014/subclasses/fiend', 'https://5e14.dnd.su/class/104-warlock/');

INSERT INTO catalog_features (id, source_kind, source_id, level, slug, name_en, name_ru, source_url, source_url_ru) VALUES
(60, 'race', 4, 1, 'dwarven-armor-training', 'Dwarven Armor Training', 'Дварфийская тренировка в доспехах',
 'https://www.dnd5eapi.co/api/2014/races/dwarf', 'https://5e14.dnd.su/race/78-dwarf/'),
(61, 'race', 5, 1, 'fleet-of-foot', 'Fleet of Foot', 'Быстрые ноги',
 'https://www.dnd5eapi.co/api/2014/races/elf', 'https://5e14.dnd.su/race/79-elf/'),
(62, 'race', 5, 1, 'mask-of-the-wild', 'Mask of the Wild', 'Маска дикой природы',
 'https://www.dnd5eapi.co/api/2014/races/elf', 'https://5e14.dnd.su/race/79-elf/'),
(63, 'race', 6, 1, 'lucky', 'Lucky', 'Удачливый',
 'https://www.dnd5eapi.co/api/2014/traits/lucky', 'https://5e14.dnd.su/race/80-halfling/'),
(64, 'race', 6, 1, 'brave', 'Brave', 'Храбрый',
 'https://www.dnd5eapi.co/api/2014/traits/brave', 'https://5e14.dnd.su/race/80-halfling/'),
(65, 'race', 6, 1, 'halfling-nimbleness', 'Halfling Nimbleness', 'Проворство полуросликов',
 'https://www.dnd5eapi.co/api/2014/traits/halfling-nimbleness', 'https://5e14.dnd.su/race/80-halfling/'),
(66, 'race', 6, 1, 'naturally-stealthy', 'Naturally Stealthy', 'Естественная скрытность',
 'https://www.dnd5eapi.co/api/2014/traits/naturally-stealthy', 'https://5e14.dnd.su/race/80-halfling/'),
(67, 'race', 7, 1, 'gnome-cunning', 'Gnome Cunning', 'Гномья хитрость',
 'https://www.dnd5eapi.co/api/2014/traits/gnome-cunning', 'https://5e14.dnd.su/race/83-gnome/'),
(68, 'race', 7, 1, 'artificers-lore', 'Artificer''s Lore', 'Знания изобретателя',
 'https://www.dnd5eapi.co/api/2014/traits/artificers-lore', 'https://5e14.dnd.su/race/83-gnome/'),
(69, 'race', 8, 1, 'draconic-ancestry', 'Draconic Ancestry', 'Драконья родословная',
 'https://www.dnd5eapi.co/api/2014/traits/draconic-ancestry', 'https://5e14.dnd.su/race/82-dragonborn/'),
(70, 'race', 8, 1, 'breath-weapon', 'Breath Weapon', 'Оружие дыхания',
 'https://www.dnd5eapi.co/api/2014/traits/breath-weapon', 'https://5e14.dnd.su/race/82-dragonborn/'),
(71, 'race', 8, 1, 'damage-resistance', 'Damage Resistance', 'Сопротивление урону',
 'https://www.dnd5eapi.co/api/2014/traits/damage-resistance', 'https://5e14.dnd.su/race/82-dragonborn/'),
(72, 'race', 9, 1, 'half-elf-darkvision', 'Darkvision', 'Тёмное зрение',
 'https://www.dnd5eapi.co/api/2014/traits/darkvision', 'https://5e14.dnd.su/race/84-half-elf/'),
(73, 'race', 9, 1, 'fey-ancestry', 'Fey Ancestry', 'Наследие фей',
 'https://www.dnd5eapi.co/api/2014/traits/fey-ancestry', 'https://5e14.dnd.su/race/84-half-elf/'),
(74, 'race', 9, 1, 'skill-versatility', 'Skill Versatility', 'Универсальность навыков',
 'https://www.dnd5eapi.co/api/2014/traits/skill-versatility', 'https://5e14.dnd.su/race/84-half-elf/'),
(75, 'race', 10, 1, 'half-orc-darkvision', 'Darkvision', 'Тёмное зрение',
 'https://www.dnd5eapi.co/api/2014/traits/darkvision', 'https://5e14.dnd.su/race/85-half-orc/'),
(76, 'race', 10, 1, 'relentless-endurance', 'Relentless Endurance', 'Непоколебимая стойкость',
 'https://www.dnd5eapi.co/api/2014/traits/relentless-endurance', 'https://5e14.dnd.su/race/85-half-orc/'),
(77, 'race', 10, 1, 'savage-attacks', 'Savage Attacks', 'Свирепые атаки',
 'https://www.dnd5eapi.co/api/2014/traits/savage-attacks', 'https://5e14.dnd.su/race/85-half-orc/'),
(78, 'race', 11, 1, 'hellish-resistance', 'Hellish Resistance', 'Адское сопротивление',
 'https://www.dnd5eapi.co/api/2014/traits/hellish-resistance', 'https://5e14.dnd.su/race/86-tiefling/'),
(79, 'race', 11, 1, 'infernal-legacy', 'Infernal Legacy', 'Инфернальное наследие',
 'https://www.dnd5eapi.co/api/2014/traits/infernal-legacy', 'https://5e14.dnd.su/race/86-tiefling/');

INSERT INTO catalog_features (id, source_kind, source_id, level, slug, name_en, name_ru, source_url, source_url_ru) VALUES
(100, 'background', 4, 1, 'false-identity', 'False Identity', 'Фальшивая личность',
 '', 'https://5e14.dnd.su/backgrounds/769-charlatan/'),
(101, 'background', 5, 1, 'criminal-contact', 'Criminal Contact', 'Преступные связи',
 '', 'https://5e14.dnd.su/backgrounds/765-criminal/'),
(102, 'background', 6, 1, 'rustic-hospitality', 'Rustic Hospitality', 'Деревенское гостеприимство',
 '', 'https://5e14.dnd.su/backgrounds/763-folk-hero/'),
(103, 'background', 7, 1, 'ships-passage', 'Ship''s Passage', 'Место на корабле',
 '', 'https://5e14.dnd.su/backgrounds/761-sailor/'),
(104, 'background', 8, 1, 'city-secrets', 'City Secrets', 'Тайны города',
 '', 'https://5e14.dnd.su/backgrounds/758-urchin/'),
(105, 'background', 9, 1, 'by-popular-demand', 'By Popular Demand', 'По многочисленным просьбам',
 '', 'https://5e14.dnd.su/backgrounds/757-entertainer/'),
(106, 'background', 10, 1, 'guild-membership', 'Guild Membership', 'Членство в гильдии',
 '', 'https://5e14.dnd.su/backgrounds/760-guild-artisan/'),
(107, 'background', 11, 1, 'position-of-privilege', 'Position of Privilege', 'Привилегированное положение',
 '', 'https://5e14.dnd.su/backgrounds/759-noble/'),
(108, 'background', 12, 1, 'discovery', 'Discovery', 'Открытие',
 '', 'https://5e14.dnd.su/backgrounds/764-hermit/'),
(109, 'background', 13, 1, 'wanderer', 'Wanderer', 'Скиталец',
 '', 'https://5e14.dnd.su/backgrounds/768-outlander/');

INSERT INTO catalog_features (id, source_kind, source_id, level, slug, name_en, name_ru, source_url, source_url_ru) VALUES
(25, 'class', 1, 5, 'extra-attack', 'Extra Attack', 'Дополнительная атака',
 'https://www.dnd5eapi.co/api/2014/features/extra-attack-1', 'https://5e14.dnd.su/class/91-fighter/'),
(26, 'class', 1, 6, 'fighter-asi-6', 'Ability Score Improvement', 'Увеличение характеристик',
 'https://www.dnd5eapi.co/api/2014/classes/fighter', 'https://5e14.dnd.su/class/91-fighter/'),
(27, 'class', 1, 9, 'indomitable', 'Indomitable', 'Упорный',
 'https://www.dnd5eapi.co/api/2014/features/indomitable-1-use', 'https://5e14.dnd.su/class/91-fighter/'),
(34, 'class', 2, 18, 'spell-mastery', 'Spell Mastery', 'Мастерство заклинателя',
 'https://www.dnd5eapi.co/api/2014/features/spell-mastery', 'https://5e14.dnd.su/class/105-wizard/'),
(35, 'class', 2, 20, 'signature-spells', 'Signature Spells', 'Фирменные заклинания',
 'https://www.dnd5eapi.co/api/2014/features/signature-spells', 'https://5e14.dnd.su/class/105-wizard/'),
(44, 'class', 3, 5, 'destroy-undead', 'Destroy Undead', 'Уничтожение нежити',
 'https://www.dnd5eapi.co/api/2014/features/destroy-undead-cr-1-2-or-below', 'https://5e14.dnd.su/class/89-cleric/'),
(45, 'class', 3, 10, 'divine-intervention', 'Divine Intervention', 'Божественное вмешательство',
 'https://www.dnd5eapi.co/api/2014/features/divine-intervention', 'https://5e14.dnd.su/class/89-cleric/');

INSERT INTO catalog_features (id, source_kind, source_id, level, slug, name_en, name_ru, source_url, source_url_ru) VALUES
(200, 'class', 4, 1, 'rage', 'Rage', 'Ярость',
 'https://www.dnd5eapi.co/api/2014/features/rage', 'https://5e14.dnd.su/class/87-barbarian/'),
(201, 'class', 4, 1, 'unarmored-defense-barbarian', 'Unarmored Defense', 'Защита без доспехов',
 'https://www.dnd5eapi.co/api/2014/features/barbarian-unarmored-defense', 'https://5e14.dnd.su/class/87-barbarian/'),
(202, 'class', 4, 2, 'reckless-attack', 'Reckless Attack', 'Безрассудная атака',
 'https://www.dnd5eapi.co/api/2014/features/reckless-attack', 'https://5e14.dnd.su/class/87-barbarian/'),
(203, 'class', 4, 2, 'danger-sense', 'Danger Sense', 'Чувство опасности',
 'https://www.dnd5eapi.co/api/2014/features/danger-sense', 'https://5e14.dnd.su/class/87-barbarian/'),
(204, 'class', 4, 3, 'primal-path', 'Primal Path', 'Путь дикости',
 'https://www.dnd5eapi.co/api/2014/features/primal-path', 'https://5e14.dnd.su/class/87-barbarian/'),
(205, 'class', 4, 4, 'barbarian-asi-4', 'Ability Score Improvement', 'Увеличение характеристик',
 'https://www.dnd5eapi.co/api/2014/classes/barbarian', 'https://5e14.dnd.su/class/87-barbarian/'),
(206, 'class', 4, 5, 'extra-attack-barbarian', 'Extra Attack', 'Дополнительная атака',
 'https://www.dnd5eapi.co/api/2014/features/extra-attack-1', 'https://5e14.dnd.su/class/87-barbarian/'),
(220, 'class', 5, 1, 'bard-spellcasting', 'Spellcasting', 'Использование заклинаний',
 'https://www.dnd5eapi.co/api/2014/features/bard-spellcasting', 'https://5e14.dnd.su/class/88-bard/'),
(221, 'class', 5, 1, 'bardic-inspiration', 'Bardic Inspiration', 'Вдохновение барда',
 'https://www.dnd5eapi.co/api/2014/features/bardic-inspiration-d6', 'https://5e14.dnd.su/class/88-bard/'),
(222, 'class', 5, 2, 'jack-of-all-trades', 'Jack of All Trades', 'Мастер на все руки',
 'https://www.dnd5eapi.co/api/2014/features/jack-of-all-trades', 'https://5e14.dnd.su/class/88-bard/'),
(223, 'class', 5, 2, 'song-of-rest', 'Song of Rest', 'Песнь отдыха',
 'https://www.dnd5eapi.co/api/2014/features/song-of-rest-d6', 'https://5e14.dnd.su/class/88-bard/'),
(224, 'class', 5, 3, 'bard-college', 'Bard College', 'Коллегия бардов',
 'https://www.dnd5eapi.co/api/2014/features/bard-college', 'https://5e14.dnd.su/class/88-bard/'),
(225, 'class', 5, 4, 'bard-asi-4', 'Ability Score Improvement', 'Увеличение характеристик',
 'https://www.dnd5eapi.co/api/2014/classes/bard', 'https://5e14.dnd.su/class/88-bard/'),
(240, 'class', 6, 1, 'druid-spellcasting', 'Spellcasting', 'Использование заклинаний',
 'https://www.dnd5eapi.co/api/2014/features/druid-spellcasting', 'https://5e14.dnd.su/class/90-druid/'),
(241, 'class', 6, 1, 'druidic', 'Druidic', 'Друидический язык',
 'https://www.dnd5eapi.co/api/2014/features/druidic', 'https://5e14.dnd.su/class/90-druid/'),
(242, 'class', 6, 2, 'wild-shape', 'Wild Shape', 'Дикий облик',
 'https://www.dnd5eapi.co/api/2014/features/wild-shape', 'https://5e14.dnd.su/class/90-druid/'),
(243, 'class', 6, 2, 'druid-circle', 'Druid Circle', 'Круг друидов',
 'https://www.dnd5eapi.co/api/2014/features/druid-circle', 'https://5e14.dnd.su/class/90-druid/'),
(244, 'class', 6, 4, 'druid-asi-4', 'Ability Score Improvement', 'Увеличение характеристик',
 'https://www.dnd5eapi.co/api/2014/classes/druid', 'https://5e14.dnd.su/class/90-druid/'),
(260, 'class', 7, 1, 'unarmored-defense-monk', 'Unarmored Defense', 'Защита без доспехов',
 'https://www.dnd5eapi.co/api/2014/features/monk-unarmored-defense', 'https://5e14.dnd.su/class/93-monk/'),
(261, 'class', 7, 1, 'martial-arts', 'Martial Arts', 'Боевые искусства',
 'https://www.dnd5eapi.co/api/2014/features/martial-arts', 'https://5e14.dnd.su/class/93-monk/'),
(262, 'class', 7, 2, 'ki', 'Ki', 'Ци',
 'https://www.dnd5eapi.co/api/2014/features/ki', 'https://5e14.dnd.su/class/93-monk/'),
(263, 'class', 7, 2, 'unarmored-movement', 'Unarmored Movement', 'Движение без доспехов',
 'https://www.dnd5eapi.co/api/2014/features/unarmored-movement', 'https://5e14.dnd.su/class/93-monk/'),
(264, 'class', 7, 3, 'monastic-tradition', 'Monastic Tradition', 'Монастырская традиция',
 'https://www.dnd5eapi.co/api/2014/features/monastic-tradition', 'https://5e14.dnd.su/class/93-monk/'),
(265, 'class', 7, 4, 'monk-asi-4', 'Ability Score Improvement', 'Увеличение характеристик',
 'https://www.dnd5eapi.co/api/2014/classes/monk', 'https://5e14.dnd.su/class/93-monk/'),
(266, 'class', 7, 5, 'extra-attack-monk', 'Extra Attack', 'Дополнительная атака',
 'https://www.dnd5eapi.co/api/2014/features/extra-attack-1', 'https://5e14.dnd.su/class/93-monk/'),
(280, 'class', 8, 1, 'divine-sense', 'Divine Sense', 'Божественное чувство',
 'https://www.dnd5eapi.co/api/2014/features/divine-sense', 'https://5e14.dnd.su/class/94-paladin/'),
(281, 'class', 8, 1, 'lay-on-hands', 'Lay on Hands', 'Наложение рук',
 'https://www.dnd5eapi.co/api/2014/features/lay-on-hands', 'https://5e14.dnd.su/class/94-paladin/'),
(282, 'class', 8, 2, 'paladin-fighting-style', 'Fighting Style', 'Боевой стиль',
 'https://www.dnd5eapi.co/api/2014/features/paladin-fighting-style', 'https://5e14.dnd.su/class/94-paladin/'),
(283, 'class', 8, 2, 'paladin-spellcasting', 'Spellcasting', 'Использование заклинаний',
 'https://www.dnd5eapi.co/api/2014/features/paladin-spellcasting', 'https://5e14.dnd.su/class/94-paladin/'),
(284, 'class', 8, 2, 'divine-smite', 'Divine Smite', 'Божественная кара',
 'https://www.dnd5eapi.co/api/2014/features/divine-smite', 'https://5e14.dnd.su/class/94-paladin/'),
(285, 'class', 8, 3, 'sacred-oath', 'Sacred Oath', 'Священная клятва',
 'https://www.dnd5eapi.co/api/2014/features/sacred-oath', 'https://5e14.dnd.su/class/94-paladin/'),
(286, 'class', 8, 4, 'paladin-asi-4', 'Ability Score Improvement', 'Увеличение характеристик',
 'https://www.dnd5eapi.co/api/2014/classes/paladin', 'https://5e14.dnd.su/class/94-paladin/'),
(287, 'class', 8, 5, 'extra-attack-paladin', 'Extra Attack', 'Дополнительная атака',
 'https://www.dnd5eapi.co/api/2014/features/extra-attack-1', 'https://5e14.dnd.su/class/94-paladin/'),
(300, 'class', 9, 1, 'favored-enemy', 'Favored Enemy', 'Избранный враг',
 'https://www.dnd5eapi.co/api/2014/features/favored-enemy-1-type', 'https://5e14.dnd.su/class/97-ranger/'),
(301, 'class', 9, 1, 'natural-explorer', 'Natural Explorer', 'Исследователь природы',
 'https://www.dnd5eapi.co/api/2014/features/natural-explorer-1-terrain-type', 'https://5e14.dnd.su/class/97-ranger/'),
(302, 'class', 9, 2, 'ranger-fighting-style', 'Fighting Style', 'Боевой стиль',
 'https://www.dnd5eapi.co/api/2014/features/ranger-fighting-style', 'https://5e14.dnd.su/class/97-ranger/'),
(303, 'class', 9, 2, 'ranger-spellcasting', 'Spellcasting', 'Использование заклинаний',
 'https://www.dnd5eapi.co/api/2014/features/ranger-spellcasting', 'https://5e14.dnd.su/class/97-ranger/'),
(304, 'class', 9, 3, 'ranger-archetype', 'Ranger Archetype', 'Архетип следопыта',
 'https://www.dnd5eapi.co/api/2014/features/ranger-archetype', 'https://5e14.dnd.su/class/97-ranger/'),
(305, 'class', 9, 4, 'ranger-asi-4', 'Ability Score Improvement', 'Увеличение характеристик',
 'https://www.dnd5eapi.co/api/2014/classes/ranger', 'https://5e14.dnd.su/class/97-ranger/'),
(306, 'class', 9, 5, 'extra-attack-ranger', 'Extra Attack', 'Дополнительная атака',
 'https://www.dnd5eapi.co/api/2014/features/extra-attack-1', 'https://5e14.dnd.su/class/97-ranger/'),
(320, 'class', 10, 1, 'expertise', 'Expertise', 'Компетентность',
 'https://www.dnd5eapi.co/api/2014/classes/rogue', 'https://5e14.dnd.su/class/99-rogue/'),
(321, 'class', 10, 1, 'sneak-attack', 'Sneak Attack', 'Скрытая атака',
 'https://www.dnd5eapi.co/api/2014/features/sneak-attack', 'https://5e14.dnd.su/class/99-rogue/'),
(322, 'class', 10, 1, 'thieves-cant', 'Thieves'' Cant', 'Воровской жаргон',
 'https://www.dnd5eapi.co/api/2014/features/thieves-cant', 'https://5e14.dnd.su/class/99-rogue/'),
(323, 'class', 10, 2, 'cunning-action', 'Cunning Action', 'Хитрое действие',
 'https://www.dnd5eapi.co/api/2014/features/cunning-action', 'https://5e14.dnd.su/class/99-rogue/'),
(324, 'class', 10, 3, 'roguish-archetype', 'Roguish Archetype', 'Архетип плута',
 'https://www.dnd5eapi.co/api/2014/features/roguish-archetype', 'https://5e14.dnd.su/class/99-rogue/'),
(325, 'class', 10, 4, 'rogue-asi-4', 'Ability Score Improvement', 'Увеличение характеристик',
 'https://www.dnd5eapi.co/api/2014/classes/rogue', 'https://5e14.dnd.su/class/99-rogue/'),
(326, 'class', 10, 5, 'uncanny-dodge', 'Uncanny Dodge', 'Невероятное уклонение',
 'https://www.dnd5eapi.co/api/2014/features/uncanny-dodge', 'https://5e14.dnd.su/class/99-rogue/'),
(340, 'class', 11, 1, 'sorcerer-spellcasting', 'Spellcasting', 'Использование заклинаний',
 'https://www.dnd5eapi.co/api/2014/features/sorcerer-spellcasting', 'https://5e14.dnd.su/class/101-sorcerer/'),
(341, 'class', 11, 1, 'sorcerous-origin', 'Sorcerous Origin', 'Происхождение чародея',
 'https://www.dnd5eapi.co/api/2014/features/sorcerous-origin', 'https://5e14.dnd.su/class/101-sorcerer/'),
(342, 'class', 11, 2, 'font-of-magic', 'Font of Magic', 'Источник магии',
 'https://www.dnd5eapi.co/api/2014/features/font-of-magic', 'https://5e14.dnd.su/class/101-sorcerer/'),
(343, 'class', 11, 3, 'metamagic', 'Metamagic', 'Метамагия',
 'https://www.dnd5eapi.co/api/2014/features/metamagic-1', 'https://5e14.dnd.su/class/101-sorcerer/'),
(344, 'class', 11, 4, 'sorcerer-asi-4', 'Ability Score Improvement', 'Увеличение характеристик',
 'https://www.dnd5eapi.co/api/2014/classes/sorcerer', 'https://5e14.dnd.su/class/101-sorcerer/'),
(360, 'class', 12, 1, 'otherworldly-patron', 'Otherworldly Patron', 'Потусторонний покровитель',
 'https://www.dnd5eapi.co/api/2014/features/otherworldly-patron', 'https://5e14.dnd.su/class/104-warlock/'),
(361, 'class', 12, 1, 'pact-magic', 'Pact Magic', 'Магия договора',
 'https://www.dnd5eapi.co/api/2014/features/pact-magic', 'https://5e14.dnd.su/class/104-warlock/'),
(362, 'class', 12, 2, 'eldritch-invocations', 'Eldritch Invocations', 'Таинственные воззвания',
 'https://www.dnd5eapi.co/api/2014/features/eldritch-invocations', 'https://5e14.dnd.su/class/104-warlock/'),
(363, 'class', 12, 3, 'pact-boon', 'Pact Boon', 'Дар покровителя',
 'https://www.dnd5eapi.co/api/2014/features/pact-boon', 'https://5e14.dnd.su/class/104-warlock/'),
(364, 'class', 12, 4, 'warlock-asi-4', 'Ability Score Improvement', 'Увеличение характеристик',
 'https://www.dnd5eapi.co/api/2014/classes/warlock', 'https://5e14.dnd.su/class/104-warlock/');

INSERT INTO catalog_features (id, source_kind, source_id, level, slug, name_en, name_ru, source_url, source_url_ru) VALUES
(600, 'subclass', 7, 3, 'frenzy', 'Frenzy', 'Френази',
 'https://www.dnd5eapi.co/api/2014/features/frenzy', 'https://5e14.dnd.su/class/87-barbarian/'),
(601, 'subclass', 8, 3, 'bonus-proficiencies-lore', 'Bonus Proficiencies', 'Дополнительные владения',
 'https://www.dnd5eapi.co/api/2014/features/bonus-proficiencies', 'https://5e14.dnd.su/class/88-bard/'),
(602, 'subclass', 8, 3, 'cutting-words', 'Cutting Words', 'Острые слова',
 'https://www.dnd5eapi.co/api/2014/features/cutting-words', 'https://5e14.dnd.su/class/88-bard/'),
(603, 'subclass', 9, 2, 'circle-spells', 'Circle Spells', 'Заклинания круга',
 'https://www.dnd5eapi.co/api/2014/subclasses/land', 'https://5e14.dnd.su/class/90-druid/'),
(604, 'subclass', 10, 3, 'open-hand-technique', 'Open Hand Technique', 'Техника открытой ладони',
 'https://www.dnd5eapi.co/api/2014/features/open-hand-technique', 'https://5e14.dnd.su/class/93-monk/'),
(605, 'subclass', 11, 3, 'sacred-weapon', 'Sacred Weapon', 'Священное оружие',
 'https://www.dnd5eapi.co/api/2014/features/sacred-weapon', 'https://5e14.dnd.su/class/94-paladin/'),
(606, 'subclass', 12, 3, 'hunters-prey', 'Hunter''s Prey', 'Добыча охотника',
 'https://www.dnd5eapi.co/api/2014/features/hunters-prey', 'https://5e14.dnd.su/class/97-ranger/'),
(607, 'subclass', 13, 3, 'fast-hands', 'Fast Hands', 'Быстрые руки',
 'https://www.dnd5eapi.co/api/2014/features/fast-hands', 'https://5e14.dnd.su/class/99-rogue/'),
(608, 'subclass', 13, 3, 'second-story-work', 'Second-Story Work', 'Странник по крышам',
 'https://www.dnd5eapi.co/api/2014/features/second-story-work', 'https://5e14.dnd.su/class/99-rogue/'),
(609, 'subclass', 14, 1, 'dragon-ancestor', 'Dragon Ancestor', 'Предок-дракон',
 'https://www.dnd5eapi.co/api/2014/features/dragon-ancestor', 'https://5e14.dnd.su/class/101-sorcerer/'),
(610, 'subclass', 14, 1, 'draconic-resilience', 'Draconic Resilience', 'Драконья устойчивость',
 'https://www.dnd5eapi.co/api/2014/features/draconic-resilience', 'https://5e14.dnd.su/class/101-sorcerer/'),
(611, 'subclass', 15, 1, 'dark-ones-blessing', 'Dark One''s Blessing', 'Благословение тёмного',
 'https://www.dnd5eapi.co/api/2014/features/dark-ones-blessing', 'https://5e14.dnd.su/class/104-warlock/');

CREATE TABLE IF NOT EXISTS catalog_items (
    id INTEGER PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name_en TEXT NOT NULL,
    name_ru TEXT NOT NULL,
    kind TEXT NOT NULL DEFAULT 'gear',
    cost_gp REAL NOT NULL DEFAULT 0,
    weight_lb REAL NOT NULL DEFAULT 0,
    damage_dice TEXT NOT NULL DEFAULT '',
    damage_type TEXT NOT NULL DEFAULT '',
    armor_class TEXT NOT NULL DEFAULT '',
    properties TEXT NOT NULL DEFAULT '[]',
    rarity TEXT NOT NULL DEFAULT '',
    source_url TEXT NOT NULL DEFAULT '',
    source_url_ru TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS catalog_spells (
    id INTEGER PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name_en TEXT NOT NULL,
    name_ru TEXT NOT NULL,
    level INTEGER NOT NULL DEFAULT 0,
    school TEXT NOT NULL DEFAULT '',
    ritual INTEGER NOT NULL DEFAULT 0,
    casting_time TEXT NOT NULL DEFAULT '',
    spell_range TEXT NOT NULL DEFAULT '',
    duration TEXT NOT NULL DEFAULT '',
    components TEXT NOT NULL DEFAULT '',
    classes TEXT NOT NULL DEFAULT '[]',
    source_url TEXT NOT NULL DEFAULT '',
    source_url_ru TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_catalog_items_kind ON catalog_items(kind);
CREATE INDEX IF NOT EXISTS idx_catalog_spells_level ON catalog_spells(level);

-- Mundane gear: 5eapi 2014 pages verified. No 5e14 /equipment/{id}-slug/ pages found; RU left empty.
INSERT INTO catalog_items (id, slug, name_en, name_ru, kind, cost_gp, weight_lb, damage_dice, damage_type, armor_class, properties, rarity, source_url, source_url_ru) VALUES
(1, 'longsword', 'Longsword', 'Длинный меч', 'weapon', 15, 3, '1d8', 'slashing', '', '["versatile"]', '',
 'https://www.dnd5eapi.co/api/2014/equipment/longsword', ''),
(2, 'dagger', 'Dagger', 'Кинжал', 'weapon', 2, 1, '1d4', 'piercing', '', '["finesse","light","thrown"]', '',
 'https://www.dnd5eapi.co/api/2014/equipment/dagger', ''),
(3, 'leather-armor', 'Leather Armor', 'Кожаный доспех', 'armor', 10, 10, '', '', '11+DEX', '["light"]', '',
 'https://www.dnd5eapi.co/api/2014/equipment/leather-armor', ''),
(4, 'shield', 'Shield', 'Щит', 'armor', 10, 6, '', '', '+2', '["shield"]', '',
 'https://www.dnd5eapi.co/api/2014/equipment/shield', ''),
(5, 'explorers-pack', 'Explorer''s Pack', 'Набор путешественника', 'gear', 10, 59, '', '', '', '[]', '',
 'https://www.dnd5eapi.co/api/2014/equipment/explorers-pack', ''),
(20, 'wand-of-fireballs', 'Wand of Fireballs', 'Волшебная палочка огненных шаров', 'wand', 0, 1, '', 'fire', '', '["attunement"]', 'rare',
 'https://www.dnd5eapi.co/api/2014/magic-items/wand-of-fireballs', 'https://5e14.dnd.su/items/20-wand-of-fireballs/'),
(21, 'potion-of-speed', 'Potion of Speed', 'Зелье скорости', 'potion', 0, 0.5, '', '', '', '[]', 'very rare',
 'https://www.dnd5eapi.co/api/2014/magic-items/potion-of-speed', 'https://5e14.dnd.su/items/68-potion-of-speed/'),
(22, 'robe-of-useful-items', 'Robe of Useful Items', 'Мантия полезных предметов', 'wondrous', 0, 4, '', '', '', '[]', 'uncommon',
 'https://www.dnd5eapi.co/api/2014/magic-items/robe-of-useful-items', 'https://5e14.dnd.su/items/130-robe-of-useful-items/'),
(23, 'flame-tongue', 'Flame Tongue', 'Язык пламени', 'weapon', 0, 3, '2d6', 'fire', '', '["attunement"]', 'rare',
 'https://www.dnd5eapi.co/api/2014/magic-items/flame-tongue', 'https://5e14.dnd.su/items/262-flame-tongue/');

-- Spells: 5e14 IDs taken from live spell pages (not guessed slugs).
INSERT INTO catalog_spells (id, slug, name_en, name_ru, level, school, ritual, casting_time, spell_range, duration, components, classes, source_url, source_url_ru) VALUES
(1, 'mage-hand', 'Mage Hand', 'Волшебная рука', 0, 'conjuration', 0, '1 action', '30 feet', '1 minute', 'V,S',
 '["bard","wizard","warlock","sorcerer"]',
 'https://www.dnd5eapi.co/api/2014/spells/mage-hand', 'https://5e14.dnd.su/spells/26-mage-hand/'),
(2, 'eldritch-blast', 'Eldritch Blast', 'Мистический заряд', 0, 'evocation', 0, '1 action', '120 feet', 'Instantaneous', 'V,S',
 '["warlock"]',
 'https://www.dnd5eapi.co/api/2014/spells/eldritch-blast', 'https://5e14.dnd.su/spells/168-eldritch-blast/'),
(3, 'bless', 'Bless', 'Благословение', 1, 'enchantment', 0, '1 action', '30 feet', 'Concentration, up to 1 minute', 'V,S,M',
 '["cleric","paladin"]',
 'https://www.dnd5eapi.co/api/2014/spells/bless', 'https://5e14.dnd.su/spells/9-bless/'),
(4, 'shield', 'Shield', 'Щит', 1, 'abjuration', 0, '1 reaction', 'Self', '1 round', 'V,S',
 '["wizard","sorcerer"]',
 'https://www.dnd5eapi.co/api/2014/spells/shield', 'https://5e14.dnd.su/spells/70-shield/'),
(5, 'cure-wounds', 'Cure Wounds', 'Лечение ран', 1, 'evocation', 0, '1 action', 'Touch', 'Instantaneous', 'V,S',
 '["bard","cleric","druid","paladin","ranger"]',
 'https://www.dnd5eapi.co/api/2014/spells/cure-wounds', 'https://5e14.dnd.su/spells/145-cure-wounds/'),
(6, 'healing-word', 'Healing Word', 'Лечащее слово', 1, 'evocation', 0, '1 bonus action', '60 feet', 'Instantaneous', 'V',
 '["bard","cleric","druid"]',
 'https://www.dnd5eapi.co/api/2014/spells/healing-word', 'https://5e14.dnd.su/spells/144-healing-word/'),
(7, 'scorching-ray', 'Scorching Ray', 'Палящий луч', 2, 'evocation', 0, '1 action', '120 feet', 'Instantaneous', 'V,S',
 '["wizard","sorcerer"]',
 'https://www.dnd5eapi.co/api/2014/spells/scorching-ray', 'https://5e14.dnd.su/spells/225-scorching-ray/'),
(8, 'fireball', 'Fireball', 'Огненный шар', 3, 'evocation', 0, '1 action', '150 feet', 'Instantaneous', 'V,S,M',
 '["wizard","sorcerer"]',
 'https://www.dnd5eapi.co/api/2014/spells/fireball', 'https://5e14.dnd.su/spells/205-fireball/');
